### ISSUE TITLE
Not Decompressing in Core 3 WebAPI App

### ISSUE THREAD

**Issue by bkonia** [alexanderkozlenko/aspnetcore-request-decompression#93]
I installed this package to my .Net Core 3.0.1 server API, then added the following to ConfgureServices:

```
            services.AddRequestDecompression(o =>
            {
                o.Providers.Add<DeflateDecompressionProvider>();
                o.Providers.Add<GzipDecompressionProvider>();
                o.Providers.Add<BrotliDecompressionProvider>();
            });
```
I then added the following line to my Configure method:
```
            app.UseRequestDecompression();
```

The API compiles fine, but when I send a Gzipped HTTP request, the server throws a 500 error with the following response:

```
Exception thrown: 'System.Net.Sockets.SocketException' in Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 POST https://localhost/ application/json 73370
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint 'PrescientAPI.Controllers.DefaultController.JsonPost (prescientAPI)'
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Route matched with {action = "JsonPost", controller = "Default"}. Executing controller action with signature System.Threading.Tasks.Task`1[Newtonsoft.Json.Linq.JObject] JsonPost(Newtonsoft.Json.Linq.JObject) on controller PrescientAPI.Controllers.DefaultController (prescientAPI).
Exception thrown: 'System.Text.DecoderFallbackException' in System.Private.CoreLib.dll
Exception thrown: 'System.Text.DecoderFallbackException' in System.Private.CoreLib.dll
Exception thrown: 'System.Text.DecoderFallbackException' in System.Private.CoreLib.dll
Exception thrown: 'System.Text.DecoderFallbackException' in System.Private.CoreLib.dll
Exception thrown: 'System.Text.DecoderFallbackException' in System.Private.CoreLib.dll
Exception thrown: 'System.Text.DecoderFallbackException' in System.Private.CoreLib.dll
Exception thrown: 'System.Text.DecoderFallbackException' in System.Private.CoreLib.dll
Exception thrown: 'System.Text.DecoderFallbackException' in System.Private.CoreLib.dll
Exception thrown: 'System.Text.DecoderFallbackException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Executed action PrescientAPI.Controllers.DefaultController.JsonPost (prescientAPI) in 416.60540000000003ms
Exception thrown: 'System.Text.DecoderFallbackException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint 'PrescientAPI.Controllers.DefaultController.JsonPost (prescientAPI)'
Exception thrown: 'System.Text.DecoderFallbackException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.Text.DecoderFallbackException: Unable to translate bytes [8B] at index 1 from specified code page to Unicode.
   at System.Text.DecoderExceptionFallbackBuffer.Throw(Byte[] bytesUnknown, Int32 index)
   at System.Text.DecoderExceptionFallbackBuffer.Fallback(Byte[] bytesUnknown, Int32 index)
   at System.Text.Encoding.GetCharsWithFallback(ReadOnlySpan`1 bytes, Int32 originalBytesLength, Span`1 chars, Int32 originalCharsLength, DecoderNLS decoder)
   at System.Text.UTF8Encoding.GetCharsWithFallback(ReadOnlySpan`1 bytes, Int32 originalBytesLength, Span`1 chars, Int32 originalCharsLength, DecoderNLS decoder)
   at System.Text.Encoding.GetCharsWithFallback(Byte* pOriginalBytes, Int32 originalByteCount, Char* pOriginalChars, Int32 originalCharCount, Int32 bytesConsumedSoFar, Int32 charsWrittenSoFar, DecoderNLS decoder)
   at System.Text.Encoding.GetChars(Byte* pBytes, Int32 byteCount, Char* pChars, Int32 charCount, DecoderNLS decoder)
   at System.Text.DecoderNLS.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, Boolean flush)
   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex, Boolean flush)
   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex)
   at Microsoft.AspNetCore.WebUtilities.HttpRequestStreamReader.ReadIntoBuffer()
   at Microsoft.AspNetCore.WebUtilities.HttpRequestStreamReader.Read(Char[] buffer, Int32 index, Int32 count)
   at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Connection: Close
Content-Type: application/json
Content-Encoding: gzip
Accept-Encoding: gzip, deflate
Host: localhost
Content-Length: 73370
```

It seems to me that it's passing the compressed data to the controller.

**Comment by alexanderkozlenko** [comment]
Yes, it seems the payload comes compressed to controllers.

- What version of the package did you use in the app?
- Did you add `app.UseRequestDecompression();` before `app.UseMvc();`?

**Comment by bkonia** [comment]
I installed it from NuGet, so it's 1.60.

I actually have `app.UseRouting()`and `app.useEndpoints()` instead of `app.UseMvc()`. Moving `app.UseRequestDecompression()` before those statements seems to have fixed the issue.

Thank you for pointing this out!
